export const FETCH_FIRE_SUCCESS = 'FETCH_FIRE_SUCCESS'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const SET_CLIENT = 'SET_CLIENT'

export const ADD_POST = 'ADD_POST'
export const SELECT_POST = 'SELECT_POST'

export const ADD_TEXT_TO_POST = 'ADD_TEXT_TO_POST'
export const SELECT_TEXT_IN_POST = 'SELECT_TEXT_IN_POST'

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
